name: "Unit Test Action"
description: "Runs mvn test"

runs:
  using: "composite"
  steps:
    - name: Check out code
      uses: actions/checkout@v4
      with:
        path: ${{ github.repository }}

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Install Maven
      run: sudo apt-get update && sudo apt-get install -y maven
      shell: bash

    - name: Cache local Maven repository
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Run unit tests
      run: mvn clean test jacoco:report
      shell: bash
