name: Component Tests

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
    outputs:
      test-result:
        description: "Result of Component Testing"
        value: ${{ jobs.test.outputs.outcome }}


jobs:
  component_tests:
    runs-on: ubuntu-latest
    outputs:
      outcome: ${{steps.status.outcome}}

    steps:
      - name: Download Release Candidate
        uses: actions/download-artifact@v4
        with:
          name: release-candidate-jar
          path: target/

      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-


      - name: Set up environment for component testing
        # Set up your component test environment here
        run: |
          echo "Setting up component test environment..."
      - name: Cucumber
        uses: actions

      - name: Run component tests
        run: |
          # Replace with your component test command
          echo "Running component tests..."

      - name: Set status
        id: status
        run: echo "outcome=true" >> $GITHUB_OUTPUT
