name: Component Tests

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      skip:
        required: false
        type: string
    outputs:
      test-result:
        description: "Result of Component Testing"
        value: ${{ jobs.test.outputs.outcome }}


jobs:
  component_tests:
    runs-on: ubuntu-latest
    outputs:
      outcome: ${{steps.status.outcome}}

    steps:
      - name: Restore repository cache
        uses: actions/cache@v4
        with:
          path: .
          key: ${{ runner.os }}-repo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-repo-${{ github.sha }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Install Maven
        run: sudo apt-get update && sudo apt-get install -y maven

      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Start test resources
        run: mvn mn:start-testresources-service

      - name: Deserialize JSON output
        id: deserialize
        uses: actions/github-script@v6
        with:
          script: |
            const output = JSON.parse(${{ inputs.skip }});
            console.log(output);
            for (const [key, value] of Object.entries(output.config)) {
              core.setOutput(key, value);
            }

      - name: Test output
        run: echo ${{ steps.deserialize.outputs.json_config }}

      - name: Run component tests
        if: ${{ steps.deserialize.outputs.json_config.config.dependency_tests }}
        run: |
          echo 
          echo "Running component tests..."
          mvn verify

      - name: Stop test resources
        run: mvn mn:stop-testresources-service

      - name: Set status
        id: status
        run: echo "outcome=true" >> $GITHUB_OUTPUT
