name: Component Tests

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  display-environment:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: Display environment
        id: environment
        uses: actions/github-script@v6
        with:
          script: |
            const environment = '${{ inputs.environment }}';
            console.log("Environment: " + environment);
            try {
              const parsed = JSON.parse(environment);
              console.log('Parsed: ' + parsed);
              for(let key in parsed) {
                if (parsed.hasOwnProperty(key)) {
                  console.log(key + ': ' + parsed[key]);
                }
              }
            } catch (error) {
              console.error("Error parsing JSON:", error);
              core.setFailed(error.message);
            }


