name: Component Tests

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  display-environment:
    runs-on: ubuntu-latest

    steps:
      - name: Display environment
        id: environment
        uses: actions/github-script@v6
        with:
          script: |
            const environment = '${{ inputs.environment }}';
            console.log("Environment: " + environment);
            core.setOutput('env', environment);
            try {
              const parsed = JSON.parse(environment);
              console.log('Parsed: ' + parsed);
              for (const [key, value] of Object.entries(output.config)) {
                console.log(key + ': ' + value);
              }
              console.log(parsed.dependency_tests);
              console.log(parsed.component_tests);
              
            } catch (error) {
              console.error("Error parsing JSON:", error);
              core.setFailed(error.message);
            }
