name: Pipeline

on:
  push:  # Run tests on all branches
    branches: ["**"]
  pull_request:  # Run tests on PRs targeting any branch
    branches: ["**"]

permissions:
  contents: write
  deployments: write

jobs:
  unit_tests:
    uses: ./.github/workflows/unit-test.yml
  build_candidate:
    needs: unit_tests
    uses: ./.github/workflows/release-candidate.yml
  component_tests:
    needs: build_candidate
    uses: ./.github/workflows/component-tests.yml
  dependency_tests:
    needs: build_candidate
    uses: ./.github/workflows/live-dependency-tests.yml
  release:
    if: github.ref == 'refs/heads/main'
    needs: [ component_tests, dependency_tests ]
    uses: ./.github/workflows/release.yml

