name: Pipeline

on:
  workflow_call:

permissions:
  contents: write
  deployments: write

jobs:
  checkout:
    uses: ./.github/workflows/checkout.yml

  read_config:
    needs: checkout
    uses: ./.github/workflows/read-config.yml

  display_environment:
    needs: read_config
    uses: ./.github/workflows/display-env.yml
    with:
      environment: ${{ needs.read_config.outputs.json-config }}

  generate_checkstyle_report:
    needs: checkout
    uses: ./.github/workflows/checkstyle.yml

  publish_checkstyle_report:
    needs: generate_checkstyle_report
    uses: ./.github/workflows/publish-checkstyle.yml

  lint:
    needs: checkout
    uses: ./.github/workflows/lint.yml

  unit_tests:
    needs: lint
    uses: ./.github/workflows/unit-test.yml

  build_candidate:
    needs: [read_config, unit_tests]
    uses: ./.github/workflows/release-candidate.yml

  component_tests:
    needs: [read_config, build_candidate]
    uses: ./.github/workflows/component-tests.yml
    with:
      configuration: ${{ needs.read_config.outputs.json-config }}

  dependency_tests:
    needs: [read_config, build_candidate]
    uses: ./.github/workflows/live-dependency-tests.yml
    with:
      configuration: ${{ needs.read_config.outputs.json-config }}

  release:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [ component_tests, dependency_tests, build_candidate ]
    uses: ./.github/workflows/release.yml
    with:
      version: ${{ needs.build_candidate.outputs.version }}
      app-name: micronautguide

