name: Pipeline Stub

on:
  workflow_call:

permissions:
  contents: write
  deployments: write

jobs:
  checkout:
    uses: ./.github/workflows/checkout.yml

  read_config:
    needs: checkout
    uses: ./.github/workflows/read-config.yml

  display_environment:
    needs: read_config
    uses: ./.github/workflows/display-env.yml
    with:
      environment: ${{ needs.read_config.outputs.json-config }}


