name: Pipeline

on:
  push:  # Run tests on all branches
    branches: ["**"]
  pull_request:  # Run tests on PRs targeting any branch
    branches: ["**"]

permissions:
  contents: write
  deployments: write

jobs:
  checkout:
    uses: ./.github/workflows/checkout.yml

  generate_checkstyle_report:
    needs: checkout
    uses: ./.github/workflows/checkstyle.yml

  upload_reports:
    needs: generate_checkstyle_report
    uses: ./.github/workflows/publish-checkstyle.yml

  lint:
    needs: checkout
    uses: ./.github/workflows/lint.yml

  unit_tests:
    needs: lint
    uses: ./.github/workflows/unit-test.yml

  build_candidate:
    needs: unit_tests
    uses: ./.github/workflows/release-candidate.yml

  component_tests:
    needs: build_candidate
    uses: ./.github/workflows/component-tests.yml
    with:
      version: ${{ needs.build_candidate.outputs.version }}

  dependency_tests:
    needs: build_candidate
    uses: ./.github/workflows/live-dependency-tests.yml
    with:
      version: ${{ needs.build_candidate.outputs.version }}

  release:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [ component_tests, dependency_tests, build_candidate ]
    uses: ./.github/workflows/release.yml
    with:
      version: ${{ needs.build_candidate.outputs.version }}
      app-name: micronautguide
