name: Upload Reports to GitHub Pages

on:
  workflow_call:

jobs:
  publish-report:
    runs-on: ubuntu-latest
    steps:
      - name: Restore repository cache
        uses: actions/cache@v4
        with:
          path: .
          key: ${{ runner.os }}-repo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-repo-${{ github.sha }}

      - name: Create or switch to documentation branch
        run: git switch -c gh-pages || git switch gh-pages

      - name: Download Checkstyle Report
        uses: actions/download-artifact@v4
        with:
          name: checkstyle-report
          path: ./reports

      - name: Check for changes
        id: git_diff
        run: |
          git diff --exit-code || echo "Changes detected"

      - name: Commit changes
        if: steps.git_diff.outputs.exit_code != '0'
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add ./reports
          git commit -m 'Update Checkstyle reports'

      - name: Push changes
        if: steps.git_diff.outputs.exit_code != '0'
        run: |
          git push origin gh-pages

      - name: Notify no changes
        if: steps.git_diff.outputs.exit_code == '0'
        run: echo "No changes to commit"