name: Read Configuration File

on:
  workflow_call:
    outputs:
      json-config:
        description: Configuration for build (from config.yml)
        value: ${{ jobs.read-config.outputs.json-config }}
        
jobs:
  read-config:
    runs-on: ubuntu-latest
    outputs:
      json-config: ${{ steps.env.outputs.json-config }}
    steps:
      - name: Restore repository cache
        uses: actions/cache@v4
        with:
          path: .
          key: ${{ runner.os }}-repo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-repo-${{ github.sha }}
      
      - name: Install yaml library
        run: npm install js-yaml

      - name: Read configuration file
        id: config
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const yaml = require('js-yaml');
            try {
              const config = yaml.load(fs.readFileSync('config.yml', 'utf8'));
              console.log("Configuration file loaded successfully:");
              console.log(config);
            
              const jsonConfig = JSON.stringify(config);
              return jsonConfig;
            } catch (error) {
              console.error("Unable to read configuration file: ", error);
              return '{}';
            }

      - name: Setup Environment
        id: env
        run: |
          echo json-config=${{ steps.config.outputs.result }} >> $GITHUB_OUTPUT
