name: Read Configuration File

on: workflow_call

jobs:
  read-config:
    runs-on: ubuntu-latest
    steps:
      - name: Restore repository cache
        uses: actions/cache@v4
        with:
          path: .
          key: ${{ runner.os }}-repo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-repo-

      - name: Install yaml library
        run: npm install js-yaml

      - name: Read configuration file
        id: config
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const yaml = require('js-yaml');
      
            try {
              const config = yaml.load(fs.readFileSync('config.yml', 'utf8'));
              console.log("Configuration file loaded successfully:");
              console.log(config);
              
              for (const [key, value] of Object.entries(config.build)) {
              console.log(`Setting output: ${key} = ${value}`);
              core.setOutput(key, value);
              }
              return config;
            } catch (error) {
              console.error("Error reading configuration file:", error);
              core.setFailed(error.message);
            }