name: Release

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      app-name:
        required: true
        type: string

permissions:
  contents: write
  deployments: write

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Download Release Candidate
        uses: actions/download-artifact@v4
        with:
          name: release-candidate-jar
          path: target/

      - name: Create GitHub Release
        if: ${{ inputs.configuration.create_release != false }}
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ inputs.version }}
          release_name: Release ${{ inputs.version }}
          body: "Automated release for commit ${{ github.sha }}"

      - name: Upload release artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: target/${{inputs.app-name}}-${{inputs.version}}.jar
          asset_name: ${{inputs.app-name}}.jar
          asset_content_type: application/java-archive
