name: Unit Tests

on:
  push:  # Run tests on all branches
    branches: ["**"]
  pull_request:  # Run tests on PRs targeting any branch
    branches: ["**"]

permissions:
  contents: write

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/unit_test/

      - name: Upload JaCoCo report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: ./target/site/jacoco/index.html

      - name: Set status
        run: |
          echo "TESTS_PASSED=true" >> $GITHUB_ENV
          echo "TESTS_PASSED=true" >> $GITHUB_OUTPUT
