name: Unit Tests

on:
  push:  # Run tests on all branches
    branches: ["**"]
  pull_request:  # Run tests on PRs targeting any branch
    branches: ["**"]

permissions:
  contents: write

jobs:
  unit_tests:
    uses: ./.github/workflows/unit-test.yml

